spring: 
  profiles: 
    active: 
    - dev

---
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-horace-dev

---

spring: 
  profiles: test
  applicatoin: 
    name: microservicecloud-config-horce-test
    